services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - tilda

  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    volumes:
      - ./:/var/www
    networks:
      - tilda

networks:
  tilda:
    driver: bridge